install_suite:
  description: Installs a suite with hassbian-config.
  fields:
    suite:
      description: 'Can be one of: hue, cloud9, mosquitto, tradfri, samba, appdaemon. [Required]'
      example: hue
upgrade_suite:
  description: Upgrades a suite with hassbian-config.
  fields:
    suite:
      description: 'Can be one of: appdaemon, cloud9, hassbian-script, homeassistant [Required]'
      example: hassbian-script
    beta:
      description: 'Can be true true or false, defaults to false [Optional]'
      example: false
    dev:
      description: 'Can be true true or false, defaults to false [Optional]'
      example: false
    version:
      description: 'Set target version for homeassistant [Optional]'
      example: 0.65.5